id: /subscriptions/3f0f20e7-c07c-412a-a061-938a6b3d1830/resourceGroups/MyResourceGroup/providers/Microsoft.App/containerapps/django-app-on-azure
identity:
  type: None
location: East Asia
name: django-app-on-azure
properties:
  configuration:
    activeRevisionsMode: Single
    dapr: null
    ingress:
      allowInsecure: false
      customDomains: null
      exposedPort: 0
      external: true
      fqdn: django-app-on-azure.icysky-ce7d1e84.eastasia.azurecontainerapps.io
      ipSecurityRestrictions: null
      targetPort: 8000
      traffic:
      - latestRevision: true
        weight: 100
      transport: Auto
    maxInactiveRevisions: null
    registries:
    - identity: ''
      passwordSecretRef: myacrtest123azurecrio-myacrtest123
      server: myacrtest123.azurecr.io
      username: myacrtest123
    secrets:
    - name: myacrtest123azurecrio-myacrtest123
  customDomainVerificationId: 8AAB8820DF7ED71C1A6D7F47A318C61937D70236479E4DED034E3310265ECF41
  environmentId: /subscriptions/3f0f20e7-c07c-412a-a061-938a6b3d1830/resourceGroups/MyResourceGroup/providers/Microsoft.App/managedEnvironments/django-app-on-azure-env
  eventStreamEndpoint: https://eastasia.azurecontainerapps.dev/subscriptions/3f0f20e7-c07c-412a-a061-938a6b3d1830/resourceGroups/MyResourceGroup/containerApps/django-app-on-azure/eventstream
  latestRevisionFqdn: django-app-on-azure--gy4y4ke.icysky-ce7d1e84.eastasia.azurecontainerapps.io
  latestRevisionName: django-app-on-azure--gy4y4ke
  managedEnvironmentId: /subscriptions/3f0f20e7-c07c-412a-a061-938a6b3d1830/resourceGroups/MyResourceGroup/providers/Microsoft.App/managedEnvironments/django-app-on-azure-env
  outboundIpAddresses:
  - 20.24.249.182
  provisioningState: Succeeded
  template:
    containers:
    - env:
      - name: TEST_VAR
        value: HELLO-WORLD
      - name: AZURE_POSTGRES_HOST
        value: django-app-on-azure-postgres-server..postgres.database.azure.com
      - name: AZURE_POSTGRES_DATABASE
        value: TEST_DATABASE
      - name: AZURE_POSTGRES_USERNAME
        value: demoadmin
      - name: AZURE_POSTGRES_PASSWORD
        value: demoadmin12345
      image: myacrtest123.azurecr.io/django-app-on-azure:9bead8b1c2943a0a9d34dc5dfa7cbc742054d654
      name: django-app-on-azure
      volumeMounts:
      - volumeName: django-app-on-azure-volume
        mountPath: /app/volume-share
      probes: []
      resources:
        cpu: 0.5
        ephemeralStorage: 1Gi
        memory: 1Gi
    initContainers: null
    revisionSuffix: ''
    scale:
      maxReplicas: 10
      minReplicas: 0
      rules: null
    volumes:
    - name: django-app-on-azure-volume
      storageName: django-app-on-azure-mount
      storageType: AzureFile
  workloadProfileType: null
resourceGroup: MyResourceGroup
systemData:
  createdAt: '2022-12-21T13:27:25.0901957'
  createdBy: admin@aresi2r12.onmicrosoft.com
  createdByType: User
  lastModifiedAt: '2022-12-22T01:54:49.5400188'
  lastModifiedBy: admin@aresi2r12.onmicrosoft.com
  lastModifiedByType: User
type: Microsoft.App/containerApps
