name: Trigger auto deployment for django-app-on-azure

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/django-app-on-azure-AutoDeployTrigger-a8677f6c-d154-46d1-940e-cb1fedca21f2.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: myacrtest123.azurecr.io
          username: ${{ secrets.DJANGOAPPONAZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.DJANGOAPPONAZURE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: myacrtest123.azurecr.io/django-app-on-azure:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DJANGOAPPONAZURE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n django-app-on-azure -g MyResourceGroup --server myacrtest123.azurecr.io --username  ${{ secrets.DJANGOAPPONAZURE_REGISTRY_USERNAME }} --password ${{ secrets.DJANGOAPPONAZURE_REGISTRY_PASSWORD }}
            az containerapp update -n django-app-on-azure -g MyResourceGroup --image myacrtest123.azurecr.io/django-app-on-azure:${{ github.sha }}
